server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abdul8377/DAD-MS2024-2.git
          search-paths: config-data
          #en caso de proyectos privados en este caso es publico por lo tanot no es necesario
          #username:
          #password:
          default-label: ms-config-server
  security:
    user:
      name: root
      password: s3cr3t